<?php
namespace App\Helpers;

class Countries
{
    public static function fetchCountries()
    {
        $arr = [];
        $arr = self::allCountries();
        $myCollection = collect($arr)->map(function($row) {
            return (object) $row;
        });
        return $myCollection;
    }

    public static function allCountries()
    {
        return [
            'countries' => [
                ['key'=>'1', 'value'=>'Afghanistan', 'code' => 'af'],
                ['key'=>'2', 'value'=>'Albania', 'code' => 'al'],
                ['key'=>'3', 'value'=>'Algeria', 'code'=>'dz'],
                ['key'=>'4', 'value'=>'Andorra', 'code'=>'ad'],
                ['key'=>'5', 'value'=>'Angola', 'code'=>'ao'],
                ['key'=>'6', 'value'=>'Antigua and Barbuda', 'code'=>'ag'],
                ['key'=>'7', 'value'=>'Argentina', 'code'=>'ar'],
                ['key'=>'8', 'value'=>'Armenia', 'code'=>'am'],
                ['key'=>'9', 'value'=>'Aruba', 'code'=>'aw'],
                ['key'=>'10', 'value'=>'Australia', 'code'=>'au'],
                ['key'=>'11', 'value'=>'Austria', 'code'=>'at'],
                ['key'=>'12', 'value'=>'Azerbaijan', 'code'=>'az'],
                ['key'=>'13', 'value'=>'Bahamas', 'code'=>'bs'],
                ['key'=>'14', 'value'=>'Bahrain', 'code'=>'bh'],
                ['key'=>'15', 'value'=>'Bangladesh', 'code'=>'bd'],
                ['key'=>'16', 'value'=>'Barbados', 'code'=>'bb'],
                ['key'=>'17', 'value'=>'Belarus', 'code'=>'by'],
                ['key'=>'18', 'value'=>'Belgium', 'code'=>'be'],
                ['key'=>'19', 'value'=>'Belize', 'code'=>'bz'],
                ['key'=>'20', 'value'=>'Benin', 'code'=>'bj'],
                ['key'=>'21', 'value'=>'Bermuda', 'code'=>'bm'],
                ['key'=>'22', 'value'=>'Bhutan', 'code'=>'bt'],
                ['key'=>'23', 'value'=>'Bolivia', 'code'=>'bo'],
                ['key'=>'24', 'value'=>'Bosnia and Herzegovina', 'code'=>'ba'],
                ['key'=>'25', 'value'=>'Botswana', 'code'=>'bw'],
                ['key'=>'26', 'value'=>'Brazil', 'code'=>'br'],
                ['key'=>'27', 'value'=>'Brunei', 'code'=>'bn'],
                ['key'=>'28', 'value'=>'Bulgaria', 'code'=>'bg'],
                ['key'=>'29', 'value'=>'Burkina Faso', 'code'=>'bf'],
                ['key'=>'30', 'value'=>'Burma (Myanmar)', 'code'=>''],
                ['key'=>'31', 'value'=>'Burundi', 'code'=>'bi'],
                ['key'=>'32', 'value'=>'Cambodia', 'code'=>'kh'],
                ['key'=>'33', 'value'=>'Cameroon', 'code'=>'cm'],
                ['key'=>'34', 'value'=>'Canada', 'code'=> 'ca'],
                ['key'=>'35', 'value'=>'Cayman Islands', 'code'=>'ky'],
                ['key'=>'36', 'value'=>'Central African Republic', 'code'=>'cf'],
                ['key'=>'37', 'value'=>'Chile', 'code'=>'cl'],
                ['key'=>'38', 'value'=>'China', 'code'=>'cn'],
                ['key'=>'39', 'value'=>'Colombia', 'code'=>'co'],
                ['key'=>'40', 'value'=>'Congo', 'code'=>'cg'],
                ['key'=>'41', 'value'=>'Costa Rica', 'code'=>'cr'],
                ['key'=>'42', 'value'=>'Croatia', 'code'=>'hr'],
                ['key'=>'43', 'value'=>'Cuba', 'code'=>'cu'],
                ['key'=>'44', 'value'=>'Cyprus', 'code'=>'cy'],
                ['key'=>'45', 'value'=>'Czech Republic', 'code'=>'cz'],
                ['key'=>'46', 'value'=>'Denmark', 'code'=>'dk'],
                ['key'=>'47', 'value'=>'Dominican Republic', 'code'=>'do'],
                ['key'=>'48', 'value'=>'Ecuador', 'code'=>'ec'],
                ['key'=>'49', 'value'=>'Egypt', 'code'=>'eg'],
                ['key'=>'50', 'value'=>'El Salvador', 'code'=>'sv'],
                ['key'=>'51', 'value'=>'Equatorial Guinea', 'code'=>'gq'],
                ['key'=>'52', 'value'=>'Estonia', 'code'=>'ee'],
                ['key'=>'53', 'value'=>'Ethiopia', 'code'=>'et'],
                ['key'=>'54', 'value'=>'Fiji', 'code'=>'fj'],
                ['key'=>'55', 'value'=>'Finland', 'code'=>'fi'],
                ['key'=>'56', 'value'=>'France', 'code'=>'fr'],
                ['key'=>'57', 'value'=>'French Guiana', 'code'=>'gf'],
                ['key'=>'58', 'value'=>'Gabon', 'code'=>'ga'],
                ['key'=>'59', 'value'=>'Gambia', 'code'=>'gm'],
                ['key'=>'60', 'value'=>'Georgia', 'code'=>'ge'],
                ['key'=>'61', 'value'=>'Germany', 'code'=>'de'],
                ['key'=>'62', 'value'=>'Ghana', 'code'=>'gh'],
                ['key'=>'63', 'value'=>'Gibraltar', 'code'=>'gi'],
                ['key'=>'64', 'value'=>'Greece', 'code'=>'gr'],
                ['key'=>'65', 'value'=>'Grenada', 'code'=>'gd'],
                ['key'=>'66', 'value'=>'Guatemala', 'code'=>'gt'],
                ['key'=>'67', 'value'=>'Guinea', 'code'=>'gn'],
                ['key'=>'68', 'value'=>'Guinea-Bissau', 'code'=>'gw'],
                ['key'=>'69', 'value'=>'Guyana', 'code'=>'gy'],
                ['key'=>'70', 'value'=>'Haiti', 'code'=>'ht'],
                ['key'=>'71', 'value'=>'Honduras', 'code'=>'hn'],
                ['key'=>'72', 'value'=>'Hong Kong', 'code'=>'hk'],
                ['key'=>'73', 'value'=>'Hungary', 'code'=>'hu'],
                ['key'=>'74', 'value'=>'Iceland', 'code'=>'is'],
                ['key'=>'75', 'value'=>'India', 'code'=>'in'],
                ['key'=>'76', 'value'=>'Indonesia', 'code'=>'id'],
                ['key'=>'77', 'value'=>'Iran', 'code'=>'ir'],
                ['key'=>'78', 'value'=>'Iraq', 'code'=>'iq'],
                ['key'=>'79', 'value'=>'Ireland', 'code'=>'ie'],
                ['key'=>'80', 'value'=>'Israel', 'code'=>'il'], 
                ['key'=>'81', 'value'=>'Italy', 'code'=>'it'],
                ['key'=>'82', 'value'=>'Ivory Coast', 'code'=>''],
                ['key'=>'83', 'value'=>'Jamaica', 'code'=>'jm'],
                ['key'=>'84', 'value'=>'Japan', 'code'=>'jp'],
                ['key'=>'85', 'value'=>'Jordan', 'code'=>'jo'],
                ['key'=>'86', 'value'=>'Kazakhstan', 'code'=>'kz'],
                ['key'=>'87', 'value'=>'Kenya', 'code'=>'ke'],
                ['key'=>'88', 'value'=>'Kuwait', 'code'=>'kw'],
                ['key'=>'89', 'value'=>'Kyrgyzstan', 'code'=>'kg'],
                ['key'=>'90', 'value'=>'Laos', 'code'=>''],
                ['key'=>'91', 'value'=>'Latvia', 'code'=>'lv'],
                ['key'=>'92', 'value'=>'Lebanon', 'code'=>'lb'],
                ['key'=>'93', 'value'=>'Lesotho', 'code'=>'ls'],
                ['key'=>'94', 'value'=>'Liberia', 'code'=>'lr'],
                ['key'=>'95', 'value'=>'Libya', 'code'=>'ly'],
                ['key'=>'96', 'value'=>'Liechtenstein', 'code'=>'li'],
                ['key'=>'97', 'value'=>'Lithuania', 'code'=>'lt'],
                ['key'=>'98', 'value'=>'Luxembourg', 'code'=>'lu'],
                ['key'=>'99', 'value'=>'Macedonia', 'code'=>''],
                ['key'=>'100', 'value'=>'Madagascar', 'code'=>'mg'],
                ['key'=>'101', 'value'=>'Malawi', 'code'=>'mw'],
                ['key'=>'102', 'value'=>'Malaysia', 'code'=>'my'],
                ['key'=>'103', 'value'=>'Maldives', 'code'=>'mv'],
                ['key'=>'104', 'value'=>'Mali', 'code'=>'ml'],
                ['key'=>'105', 'value'=>'Malta', 'code'=>'mt'],
                ['key'=>'106', 'value'=>'Mauritania', 'code'=>'mr'],
                ['key'=>'107', 'value'=>'Mauritius', 'code'=>'mu'],
                ['key'=>'108', 'value'=>'Mexico', 'code'=>'mx'],
                ['key'=>'109', 'value'=>'Moldova', 'code'=>'md'],
                ['key'=>'110', 'value'=>'Monaco', 'code'=>'mc'],
                ['key'=>'111', 'value'=>'Mongolia', 'code'=>'mn'],
                ['key'=>'112', 'value'=>'Montenegro', 'code'=>'me'],
                ['key'=>'113', 'value'=>'Morocco', 'code'=>'ma'],
                ['key'=>'114', 'value'=>'Mozambique', 'code'=>'mz'],
                ['key'=>'115', 'value'=>'Namibia', 'code'=>'na'],
                ['key'=>'116', 'value'=>'Nepal', 'code'=>'np'],
                ['key'=>'117', 'value'=>'Netherlands', 'code'=>'nl'],
                ['key'=>'118', 'value'=>'Netherlands Antilles', 'code'=>''],
                ['key'=>'119', 'value'=>'New Caledonia', 'code'=>'cn'],
                ['key'=>'120', 'value'=>'New Zealand', 'code'=>'nz'],
                ['key'=>'121', 'value'=>'Nicaragua', 'code'=>'ni'],
                ['key'=>'122', 'value'=>'Niger', 'code'=>'ne'],
                ['key'=>'123', 'value'=>'Nigeria', 'code'=>'ng'],
                ['key'=>'124', 'value'=>'North Korea', 'code'=>''],
                ['key'=>'125', 'value'=>'Norway', 'code'=>'no'],
                ['key'=>'126', 'value'=>'Oman', 'code'=>'om'],
                ['key'=>'127', 'value'=>'Pakistan', 'code'=>'pk'],
                ['key'=>'128', 'value'=>'Palestine', 'code'=>'ps'],
                ['key'=>'129', 'value'=>'Panama', 'code'=>'pa'],
                ['key'=>'130', 'value'=>'Papua New Guinea', 'code'=>'pg'],
                ['key'=>'131', 'value'=>'Paraguay', 'code'=>'py'],
                ['key'=>'132', 'value'=>'Peru', 'code'=>'pe'],
                ['key'=>'133', 'value'=>'Philippines', 'code'=>'ph'],
                ['key'=>'134', 'value'=>'Poland', 'code'=>'pl'],
                ['key'=>'135', 'value'=>'Portugal', 'code'=>'pt'],
                ['key'=>'136', 'value'=>'Puerto Rico', 'code'=>'pr'],
                ['key'=>'137', 'value'=>'Qatar', 'code'=>'qa'],
                ['key'=>'138', 'value'=>'Reunion', 'code'=>'re'],
                ['key'=>'139', 'value'=>'Romania', 'code'=>'ro'],
                ['key'=>'140', 'value'=>'Russia', 'code'=>'ru'],
                ['key'=>'141', 'value'=>'Rwanda', 'code'=>'rw'],
                ['key'=>'142', 'value'=>'Saint Lucia', 'code'=>'lc'],
                ['key'=>'143', 'value'=>'Saudi Arabia', 'code'=>'sa'],
                ['key'=>'144', 'value'=>'Senegal', 'code'=>'sn'],
                ['key'=>'145', 'value'=>'Serbia', 'code'=>'rs'],
                ['key'=>'146', 'value'=>'Sierra Leone', 'code'=>'sl'],
                ['key'=>'147', 'value'=>'Singapore', 'code'=>'sg'],
                ['key'=>'148', 'value'=>'Slovakia', 'code'=>'sk'],
                ['key'=>'149', 'value'=>'Slovenia', 'code'=>'si'],
                ['key'=>'150', 'value'=>'Somalia', 'code'=>'so'],
                ['key'=>'151', 'value'=>'South Africa', 'code'=>'za'],
                ['key'=>'152', 'value'=>'South Korea', 'code'=>''],
                ['key'=>'153', 'value'=>'Spain', 'code'=>'es'],
                ['key'=>'154', 'value'=>'Sri Lanka', 'code'=>'lk'],
                ['key'=>'155', 'value'=>'Sudan', 'code'=>'sd'],
                ['key'=>'156', 'value'=>'Suriname', 'code'=>'sr'],
                ['key'=>'157', 'value'=>'Swaziland', 'code'=>'ch'],
                ['key'=>'158', 'value'=>'Sweden', 'code'=>'se'],
                ['key'=>'159', 'value'=>'Switzerland', 'code'=>'ch'],
                ['key'=>'160', 'value'=>'Syria', 'code'=>'sy'],
                ['key'=>'161', 'value'=>'Taiwan', 'code'=>'tw'],
                ['key'=>'162', 'value'=>'Tajikistan', 'code'=>'tj'],
                ['key'=>'163', 'value'=>'Tanzania', 'code'=>'tz'],
                ['key'=>'164', 'value'=>'Thailand', 'code'=>'th'],
                ['key'=>'165', 'value'=>'Togo', 'code'=>'tg'],
                ['key'=>'166', 'value'=>'Trinidad and Tobago', 'code'=>'tt'],
                ['key'=>'167', 'value'=>'Tunisia', 'code'=>'nt'],
                ['key'=>'168', 'value'=>'Turkey', 'code'=>'tr'],
                ['key'=>'169', 'value'=>'Turkmenistan', 'code'=>'tm'],
                ['key'=>'170', 'value'=>'Uganda', 'code'=>'ug'],
                ['key'=>'171', 'value'=>'Ukraine', 'code'=>'ua'],
                ['key'=>'172', 'value'=>'United Arab Emirates', 'code'=>'ae'],
                ['key'=>'173', 'value'=>'United Kingdom', 'code'=>'gb'],
                ['key'=>'174', 'value'=>'United States', 'code'=>'us'],
                ['key'=>'175', 'value'=>'Uruguay', 'code'=>'uy'],
                ['key'=>'176', 'value'=>'Uzbekistan', 'code'=>'uz'],
                ['key'=>'177', 'value'=>'Venezuela', 'code'=>'vu'],
                ['key'=>'178', 'value'=>'Vietnam', 'code'=>'vn'],
                ['key'=>'179', 'value'=>'Yemen', 'code'=>'ye'],
                ['key'=>'180', 'value'=>'Yugoslavia', 'code'=>''],
                ['key'=>'181', 'value'=>'Zambia', 'code'=>'zm'],
                ['key'=>'182', 'value'=>'Zimbabwe', 'code'=>'zw']
            ]
        ];
    }
}